services:
    app:
        container_name: contta-container
        environment:
            DB_SERVER: ${DB_SERVER}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/var/www/html/app
            - ./assets:/var/www/html/assets
            - ./plugin:/var/www/html/plugin
            - ./index.html:/var/www/html/index.html
        ports:
            - "${APP_PORT}:80"
        networks:
            - contta-network
        tty: true

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        restart: always
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - contta-network

    db:
        image: mysql:5.7
        container_name: mysqldb-container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - contta-network

networks:
    contta-network:
        name: contta-network
        external: false